### ISSUE TITLE
Cannot pin long commands

### ISSUE THREAD

**Issue by lethalgem** [acrucetta/pin#1]
```zsh
pin add "/usr/bin/env /Library/Java/JavaVirtualMachines/jdk-17.0.2.jdk/Contents/Home/bin/java -XX:+ShowCodeDetailsInExceptionMessages -cp $HOME/Library/Application\ Support/Code/User/workspaceStorage/2f09ce04a4ec3139360fad4effb1b743/redhat.java/jdt_ws/crafting-interpreters-turf_2c293026/bin com.craftinginterpretersturf.lox.Lox"
```

results in 
```zsh
Successfully added command /usr/bin/env /Library/Java/JavaVirtualMachines/jdk-17.0.2.jdk/Contents/Home/bin/java -XX:+ShowCodeDetailsInExceptionMessages -cp /Users/iancash/Library/Application\ Support/Code/User/workspaceStorage/2f09ce04a4ec3139360fad4effb1b743/redhat.java/jdt_ws/crafting-interpreters-turf_2c293026/bin com.craftinginterpretersturf.lox.Lox

pin ls
...
3: /usr/bin/env /Library/Java/JavaVirtualMachines/jdk-17.0.2.jdk/Contents/Home/bin/java -XX:+ShowCodeD4: etailsInExceptionMessages -cp /Users/iancash/Library/Application\ Support/Code/User/workspaceStorag5: e/2f09ce04a4ec3139360fad4effb1b743/redhat.java/jdt_ws/crafting-interpreters-turf_2c293026/bin com.c6: raftinginterpretersturf.lox.Lox
```

Specifically the error is with extra/incorrect characters in the saved command (highlighted below). And the command is modified. Instead of preserving `$HOME`, it evaluates and becomes `/Users/iancash/`
```zsh
/usr/bin/env /Library/Java/JavaVirtualMachines/jdk-17.0.2.jdk/Contents/Home/bin/java -XX:+ShowCodeDetailsInExceptionMessages -cp $HOME/Library/Application\ Support/Code/User/workspaceStorage/2f09ce04a4ec3139360fad4effb1b743/redhat.java/jdt_ws/crafting-interpreters-turf_2c293026/bin com.craftinginterpretersturf.lox.Lox"
```
becomes 

```zsh
/usr/bin/env /Library/Java/JavaVirtualMachines/jdk-17.0.2.jdk/Contents/Home/bin/java -XX:+ShowCode**D4:** etailsInExceptionMessages -cp /Users/iancash/Library/Application\ Support/Code/User/workspaceStorag**5:** e/2f09ce04a4ec3139360fad4effb1b743/redhat.java/jdt_ws/crafting-interpreters-turf_2c293026/bin com**.c6:** raftinginterpretersturf.lox.Lox
```

I expect it to result in 
```zsh
Successfully added command /usr/bin/env /Library/Java/JavaVirtualMachines/jdk-17.0.2.jdk/Contents/Home/bin/java -XX:+ShowCodeDetailsInExceptionMessages -cp $HOME/Library/Application\ Support/Code/User/workspaceStorage/2f09ce04a4ec3139360fad4effb1b743/redhat.java/jdt_ws/crafting-interpreters-turf_2c293026/bin com.craftinginterpretersturf.lox.Lox

pin ls
...
3: /usr/bin/env /Library/Java/JavaVirtualMachines/jdk-17.0.2.jdk/Contents/Home/bin/java -XX:+ShowCodeDetailsInExceptionMessages -cp $HOME/Library/Application\ Support/Code/User/workspaceStorage/2f09ce04a4ec3139360fad4effb1b743/redhat.java/jdt_ws/crafting-interpreters-turf_2c293026/bin com.craftinginterpretersturf.lox.Lox
```

**Comment by lethalgem** [comment]
~~@acrucetta If I manually added this to my command store file it would work around this issue right?~~

Actually it results in this command being run through `pin run`

```zsh
/usr/bin/env /Library/Java/JavaVirtualMachines/jdk-17.0.2.jdk/Contents/Home/bin/java -XX:+ShowCodeD4: etailsInExceptionMessages -cp $HOME/Library/Application\ Support/Code/User/workspaceStorage/2f09ce05: 4a4ec3139360fad4effb1b743/redhat.java/jdt_ws/crafting-interpreters-turf_2c293026/bin com.craftingin6: terpretersturf.lox.Lox
```

It looks like the issue is what is happening after the command is read from the file

**Comment by acrucetta** [comment]
I think the issue is that it thinks the command is split into multiple
commands. Can you try adding quotes around it and see if it works?

- Andrés Crucetta
andrescn.me <https://andrescn.me>

On January 30, 2024, Github ***@***.***> wrote:
> @acrucetta <https://github.com/acrucetta> If I manually added this to
> my command store file it would work around this issue right?
>

—
Reply to this email directly, view it on GitHub
<https://github.com/acrucetta/pin/issues/1#issuecomment-1917445299>, or
unsubscribe <https://github.com/notifications/unsubscribe-
auth/AGDNHX5C2QKBVCY4VW6XV2TYREOW7AVCNFSM6AAAAABCRRBQPWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSMJXGQ2DKMRZHE>.
You are receiving this because you were mentioned.Message ID:
***@***.***>

**Comment by lethalgem** [comment]
The command that is failing has quotes around it 

```zsh
pin add "/usr/bin/env /Library/Java/JavaVirtualMachines/jdk-17.0.2.jdk/Contents/Home/bin/java -XX:+ShowCodeDetailsInExceptionMessages -cp $HOME/Library/Application\ Support/Code/User/workspaceStorage/2f09ce04a4ec3139360fad4effb1b743/redhat.java/jdt_ws/crafting-interpreters-turf_2c293026/bin com.craftinginterpretersturf.lox.Lox"
```

if I add quotes into the config file the run command will fail with 
```
sh: -c: line 0: unexpected EOF while looking for matching `"'
```

**Comment by acrucetta** [comment]
Oh word, ok I'll take a look

- Andrés Crucetta
andrescn.me <https://andrescn.me>

On January 30, 2024, Github ***@***.***> wrote:
> The command that is failing has quotes around it
>
> pin add "/usr/bin/env /Library/Java/JavaVirtualMachines/jdk-
> 17.0.2.jdk/Contents/Home/bin/java -
> XX:+ShowCodeDetailsInExceptionMessages -cp $HOME/Library/Application\
> Support/Code/User/workspaceStorage/2f09ce04a4ec3139360fad4effb1b743/redhat.java/jdt_ws/crafting-
> interpreters-turf_2c293026/bin com.craftinginterpretersturf.lox.Lox"
> if I add quotes into the config file the run command will fail with
> sh: -c: line 0: unexpected EOF while looking for matching "'`
>

—
Reply to this email directly, view it on GitHub
<https://github.com/acrucetta/pin/issues/1#issuecomment-1917572889>, or
unsubscribe <https://github.com/notifications/unsubscribe-
auth/AGDNHX6Y7MOST727632GL7LYREWVHAVCNFSM6AAAAABCRRBQPWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSMJXGU3TEOBYHE>.
You are receiving this because you were mentioned.Message ID:
***@***.***>

**Comment by acrucetta** [comment]
I've increased the command length to 500 so it should be working now>

```
5: /usr/bin/env /Library/Java/JavaVirtualMachines/jdk-17.0.2.jdk/Contents/Home/bin/java -XX:+ShowCodeDetailsInExceptionMessages -cp /Users/andrescru/Library/Application\ Support/Code/User/workspaceStorage/2f09ce04a4ec3139360fad4effb1b743/redhat.java/jdt_ws/crafting-interpreters-turf_2c293026/bin com.craftinginterpretersturf.lox.Lox
```
